const MOVE_SPEED = 120;
const JUMP_FORCE = 360;
const BIG_JUMP_FORCE = 500;
const ENEMY_SPEED = 20;
const MUSHROOM_SPEED = ENEMY_SPEED;
const FALL_DEATH = 400;

export const constants = {
    MOVE_SPEED,
    JUMP_FORCE,
    BIG_JUMP_FORCE,
    MUSHROOM_SPEED,
    FALL_DEATH,
    ENEMY_SPEED,
}